#datasource specific properties - t 

spring:  data:    mongodb:#      uri: mongodb://0.0.0.0:27017/trainingdb
       uri: mongodb://mongodb:27017/trainingdb
server:
  port: 8081
jwt:
 secret: secret code

logging:  level:    root: DEBUG
    '[org.springframework]': DEBUG
    '[com.bookapp]': DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] -> %msg%n'    